# Generated by Django 5.1.5 on 2025-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], default='client', max_length=50),
        ),
        migrations.AlterField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
    ]
