# Generated by Django 5.1.5 on 2025-01-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_utilisateurs_role_alter_utilisateurs_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
