# Generated by Django 5.1.2 on 2025-02-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_utilisateurs_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('duree', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='En attente', max_length=50)),
                ('id_immobilier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.immobiliers')),
            ],
        ),
    ]
