# Generated by Django 5.1.2 on 2025-03-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_demandes'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobiliers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
