# Generated by Django 5.1 on 2025-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_demandes_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
