version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
    volumes:
      - ./backend:/app  # Mount the entire backend folder
    command: python manage.py runserver 0.0.0.0:8000  # Run the Django backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev  # Run the frontend with Vite

volumes:
  sqlite_data:
