name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Déclenche l'action sur un push vers la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # L'action s'exécute sur un environnement Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clone le dépôt dans l'environnement de l'action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configure Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Se connecte à Docker Hub en utilisant les secrets du dépôt
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gri-backend:latest ./backend  # Utilise le Dockerfile du backend
          docker push ${{ secrets.DOCKER_USERNAME }}/gri-backend:latest  # Pousse l'image vers Docker Hub

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gri-frontend:latest ./frontend  # Utilise le Dockerfile du frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/gri-frontend:latest  # Pousse l'image vers Docker Hub
